### ISSUE TITLE
Halloween chat background

### ISSUE THREAD

**Issue by amishshah** [unicsmcr/unics_social#126]
For the upcoming Halloween KB event, the Graphics team has made a Halloween chat background (see the graphics channel for the image).

A branch `theme/halloween` should be made from `main`. A separate branch should then be made from this branch, e.g. `feat/halloween-background` that uses the Halloween background if the date on the user's machine is 30th October - 1st November, otherwise it uses the default.

A pull request should then be made from this branch to `theme/halloween`.

**Comment by Quindrix** [comment]
This was harder than I expected it to be. I'm removing my assignment while I learn TypeScript properly. 😅

**Comment by Quindrix** [comment]
Resolved by #131
