### ISSUE TITLE
redux-basic-store

### ISSUE THREAD

**Issue by zainja** [unicsmcr/unics_social#2]
implementing the store for the general user required fields

- Username
- email
- token

**Comment by HishamAlyahya** [comment]
@zainja just set up a basic store b99a6a36344e1375fb10fd0477e3deacaa1abe25 lemme know if you have any comments

**Comment by zainja** [comment]
im gonna edit the current redux is it just auth and channels right ?

**Comment by HishamAlyahya** [comment]
yep

**Comment by zainja** [comment]
it is done
