### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by amishshah** [unicsmcr/unics_social#36]
We need a contact us page, this could be something that is as simple as just linking a contact email.

**Comment by asharonbaltazar** [comment]
Hello, I'd like to try my hand at this. What are your specifications for the contact page?

**Comment by amishshah** [comment]
Hi @asharonbaltazar, are you a member of UniCS? While these repos are public, development is mainly targeted for members of UniCS, and this issue in particular is one I'd like to leave to a member of UniCS.

**Comment by asharonbaltazar** [comment]
I am not. I just found this on an issue aggregator. Will keep looking for other things to tackle.

**Comment by amishshah** [comment]
Resolved
