### ISSUE TITLE
Account settings "contact us" text should link to contact us page

### ISSUE THREAD

**Issue by amishshah** [unicsmcr/unics_social#37]
![image](https://user-images.githubusercontent.com/10330923/92304773-e7a9cb80-ef78-11ea-9079-04ca2bf85848.png)

The "contact us" text here should link to a contact us page. This is blocked by #36.

**Comment by soumyarup-paul** [comment]
Hi, can you please assign this to me?
PR - https://github.com/unicsmcr/unics_social/pull/120

**Comment by soumyarup-paul** [comment]
Hi, 
Can you please add Hacktoberfest label to this issue? This will serve as my first PR.
Regards,
Soumyarup Paul
